### ISSUE TITLE
python script might be in bin for some users 

### ISSUE THREAD

**Issue by ghost** [Perif/MatrixMarketToPETSc#1]
Thanks for good code, I just noticed that the below path didn't work for me.
sys.path.insert(0, dirs+'/bin/pythonscripts/')
My PETSc files are located in bin directory and I used below line instead.
sys.path.insert(0, dirs+'/bin/')

**Comment by Perif** [comment]
Thanks ! 

This directory has been added in the path. Please let me know if you still encounter an issue.

Regards.
